"""le_extract — offline Lone Echo archive -> .lemesh package extractor.

Stage 1 of the Blender tool. MUST run under Windows Python so `le_oodle` can load
the game Oodle DLL:

    python.exe blender_tool/extractor/le_extract.py --archive 0703fd2acd5803e9 --mesh 8f76d470b7ca990f
    python.exe blender_tool/extractor/le_extract.py --archive 0703fd2acd5803e9 --all
    python.exe blender_tool/extractor/le_extract.py --archive 0703fd2acd5803e9 --list

Reuses the decode stack in this repo's `scripts/` (le_oodle, le_archive_decode,
le_meshlist_decode) to reach decompressed primary/GPU subresource slices, then
hands the bytes to the pure-stdlib le_mesh core to decode every vertex attribute
and write the package.

Milestones:
  M1 (this stage): full-attribute geometry + draws + flags + LOD metadata.   [DONE]
  M2: material role/texture bindings + SGMaterialData scalars + DDS texture
      extraction (incl. cross-archive homes).                                 [DONE]
      Roles are resolved LIVE FROM THE ARCHIVE by default. `--tsv-materials`
      switches back to precomputed scan TSVs, which only cover whatever
      archives you generated them for.
      Flags: --textures (extract DDS), --tsv-materials (legacy TSV resolution).

CROSS-ARCHIVE RESOLUTION — READ THIS BEFORE YOU TRUST A PACKAGE
---------------------------------------------------------------
Neither textures nor materials live in the archive that binds them:

  * shadersets are 100 % resident in the binding archive, but the TEXTURES they
    bind mostly are not (88 of 115 bindings are external on archive
    `0703fd2acd5803e9`; 31 of 31 on `4a405738bee7a74b`);
  * MATERIALS are only ~19 % resident (24 of 127 bindings on `0703fd2acd5803e9`).

A resolver that assumes local therefore fails SILENTLY: a missed texture is
simply not extracted, and a missed material falls back to `SGMaterialData`
defaults, so an `eMTForwardTransparent` material reads as mattype 0 /
eBlendOpaque and renders opaque.

Two corpus-wide indexes fix that, and they are YOUR data — generate them once
from your own game install into `$LONE_ECHO_SCAN_ROOT`:

    python.exe scripts\\le_texture_archive_index.py     -> texture_archive_index.tsv
    python.exe scripts\\le_material_archive_index.py    -> material_archive_index.tsv

Without them this extractor still runs, but it warns loudly and resolves far
fewer bindings. See the README's "Build the corpus indexes" section.
"""

from __future__ import annotations

import argparse
import csv
import os
import struct
import sys
from pathlib import Path

# --- path wiring: this file is <repo>/blender_tool/extractor/… ---
THIS = Path(__file__).resolve()
BLENDER_TOOL = THIS.parents[1]
REPO_ROOT = THIS.parents[2]
SCRIPTS = REPO_ROOT / "scripts"
for p in (str(BLENDER_TOOL), str(SCRIPTS)):
    if p not in sys.path:
        sys.path.insert(0, p)

# proven decode stack (Windows-python + Oodle)
from le_oodle import load_decompressed                       # noqa: E402
from le_archive_decode import (                    # noqa: E402
    ARCHIVE_GPU, ARCHIVE_PRIMARY, DEFAULT_HASH_LOOKUP,
    archive_offsets, entry_at, load_hash_lookup, parse_header, resource_entries,
)
from le_meshlist_decode import parse_candidate   # noqa: E402
# proven material / texture / binding decoders (reused, not reimplemented)
import le_scene_binding as sb                # noqa: E402
import le_shaderset_scan as sts            # noqa: E402
import le_material_slice as msp              # noqa: E402
from le_texture_extract import collect_resource_map   # noqa: E402

# pure-stdlib core + extractor helpers
from le_mesh import meshlist as ml                           # noqa: E402
from le_mesh import materials as mat                         # noqa: E402
from le_mesh import material_scalars as msc                  # noqa: E402
from le_mesh import package as pkg                           # noqa: E402
import le_textures                                           # noqa: E402

# Windows consoles default to cp1252 and argparse echoes this module's docstring
# on --help, so any non-ASCII in it raises UnicodeEncodeError the moment stdout
# is not a console (a pipe, a redirect, CI). Force UTF-8 on the streams we own.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):   # already-wrapped or non-reconfigurable
        pass

# Optional precomputed scan inputs, all under `LONE_ECHO_SCAN_ROOT`. You generate
# these from your own game install; none of them ship with this repository.
SCAN_ROOT = Path(os.environ.get("LONE_ECHO_SCAN_ROOT",
                                str(REPO_ROOT / "scan_inputs")))
BINDING_TSV = SCAN_ROOT / "scene_binding_parse.tsv"
SCAN_TSV = SCAN_ROOT / "combined_shader_scan.tsv"
TEX_MANIFESTS = [SCAN_ROOT / "texture_manifest.tsv"]

# --- the two corpus-wide indexes ------------------------------------------
# Both are generated by a script in `scripts/` over YOUR archives; see the module
# docstring. Absence is survivable but NOT silent -- `warn_missing_indexes()`
# prints exactly what is lost.

# tex_hash -> the archive that owns the texture.
# This index is what makes cross-archive role resolution work at all. Shadersets
# overwhelmingly bind textures homed in OTHER archives, so gating the
# SShaderInputData scan on archive-local texture hashes finds almost nothing:
# 88 of 115 bindings are external on the reference archive 0703fd2acd5803e9, and
# 31 of 31 on 4a405738bee7a74b (which resolved 0 roles for exactly this reason).
TEX_INDEX_TSV = SCAN_ROOT / "texture_archive_index.tsv"

# material_hash -> the archive that owns it. Materials are only ~19 % resident in
# the archive that BINDS them (127 bindings, 24 resident on 0703fd2acd5803e9)
# while shadersets are 100 % resident -- so without this, every non-resident
# material silently falls back to SGMaterialData defaults and reads downstream as
# an ordinary opaque material.
MAT_INDEX_TSV = SCAN_ROOT / "material_archive_index.tsv"

_GLOBAL_TEX_INDEX: dict[int, str] | None = None
_GLOBAL_MAT_INDEX: dict[str, str] | None = None


def load_global_texture_index(path: Path = TEX_INDEX_TSV) -> dict[int, str]:
    """tex_hash(int) -> home archive hash. Cached; {} when the index is absent."""
    global _GLOBAL_TEX_INDEX
    if _GLOBAL_TEX_INDEX is None:
        idx: dict[int, str] = {}
        p = Path(path)
        if p.exists():
            with p.open(encoding="utf-8", newline="") as fh:
                for row in csv.DictReader(fh, delimiter="\t"):
                    try:
                        idx[int(row["tex_hash"], 16)] = row["archive_hash"]
                    except (KeyError, ValueError):
                        continue
        _GLOBAL_TEX_INDEX = idx
    return _GLOBAL_TEX_INDEX


def load_global_material_index(path: Path = MAT_INDEX_TSV) -> dict[str, str]:
    """material_hash(16-hex) -> home archive hash. Cached; {} when absent."""
    global _GLOBAL_MAT_INDEX
    if _GLOBAL_MAT_INDEX is None:
        idx: dict[str, str] = {}
        p = Path(path)
        if p.exists():
            with p.open(encoding="utf-8", newline="") as fh:
                for row in csv.DictReader(fh, delimiter="\t"):
                    try:
                        idx[row["material_hash"].lower()] = row["archive_hash"]
                    except KeyError:
                        continue
        _GLOBAL_MAT_INDEX = idx
    return _GLOBAL_MAT_INDEX


def warn_missing_indexes(out=print) -> list[str]:
    """Say out loud what an absent corpus index costs. Returns the warnings.

    Degrading to local-only resolution is EXACTLY the bug these indexes exist to
    fix, so it must never happen quietly.
    """
    warnings = []
    if not Path(TEX_INDEX_TSV).exists():
        warnings.append(
            f"WARN no texture archive index at {TEX_INDEX_TSV} — texture roles "
            f"will resolve ONLY for textures that happen to live in this same "
            f"archive. On shipped levels that is a small minority of bindings "
            f"(27 of 115 on one reference archive, 0 of 31 on another), so most "
            f"materials will come out with no maps at all. "
            f"Generate it with scripts/le_texture_archive_index.py.")
    if not Path(MAT_INDEX_TSV).exists():
        warnings.append(
            f"WARN no material archive index at {MAT_INDEX_TSV} — only materials "
            f"resident in this archive (~19 %) get their real SGMaterialData "
            f"scalars. The rest fall back to defaults and will read as opaque, "
            f"non-emissive materials. "
            f"Generate it with scripts/le_material_archive_index.py.")
    for w in warnings:
        out(w)
    return warnings


def _primary_offsets(primary: bytes) -> tuple[int, int]:
    """(data_off, header_off) from a decompressed primary alone (no GPU needed).

    The primary's two header blocks enumerate both primary and GPU entries, so a
    foreign archive can be probed for material slices without decompressing its
    (much larger) GPU file.
    """
    primary_size = struct.unpack_from("<Q", primary, 0)[0]
    extra_skip = struct.unpack_from("<Q", primary, 0x18)[0]
    data_off = 0x20 + extra_skip
    return data_off, data_off + primary_size


_FOREIGN_SCALAR_CACHE: dict[str, dict] = {}


def foreign_material_scalars(wanted: dict[str, str], *, verbose: bool = False) -> dict:
    """{material_hash -> scalars} for materials living in OTHER archives.

    `wanted` maps material_hash -> home archive hash. Grouped by home and loaded
    ONE ARCHIVE AT A TIME, dropping each decompressed primary before opening the
    next, so peak memory stays at a single archive rather than the union.

    Results are cached process-wide: `--all` resolves materials per mesh-list and
    the same foreign material is bound by many of them, so without the cache a
    51-mesh-list run would re-decompress the same home archives 51 times.
    """
    by_home: dict[str, set[str]] = {}
    out: dict[str, dict] = {}
    for mh, home in wanted.items():
        hit = _FOREIGN_SCALAR_CACHE.get(mh)
        if hit is not None:
            out[mh] = hit
        else:
            by_home.setdefault(home, set()).add(mh)
    if not by_home:
        return out

    for home, hashes in sorted(by_home.items()):
        path = ARCHIVE_PRIMARY / home
        if not path.exists() or _compressed_stub(path):
            continue
        primary = None
        try:
            primary = load_decompressed(path)
            data_off, header_off = _primary_offsets(primary)
            mmap_ = collect_resource_map(primary, header_off, msp.MATERIAL_TYPE)
            for mh in hashes:
                ent = mmap_.get(int(mh, 16))
                if ent is None:
                    continue
                _idx, pos, size = ent
                sc = msc.decode_material_scalars(
                    primary[data_off + pos: data_off + pos + size])
                out[mh] = _FOREIGN_SCALAR_CACHE[mh] = sc
            if verbose:
                print(f"    foreign materials from {home}: "
                      f"{sum(1 for h in hashes if h in out)}/{len(hashes)}")
        except Exception as exc:   # noqa: BLE001
            print(f"    WARN foreign material archive {home}: {exc}")
        finally:
            primary = None   # noqa: F841  drop before opening the next archive
    return out


def _compressed_stub(path: Path) -> bool:
    return path.exists() and path.stat().st_size in (44, 57)


class Archive:
    """Loaded + decompressed archive with resolved mesh-list resource tables."""

    def __init__(self, archive_hash: str, names: dict):
        self.hash = archive_hash
        self.names = names
        primary_path = ARCHIVE_PRIMARY / archive_hash
        gpu_path = ARCHIVE_GPU / archive_hash
        if _compressed_stub(primary_path) or _compressed_stub(gpu_path):
            raise RuntimeError(f"archive {archive_hash} is a compressed stub")
        self.primary = load_decompressed(primary_path)
        self.gpu = load_decompressed(gpu_path)
        _, _, self.data_off, self.header_off = archive_offsets(self.primary, self.gpu)
        header0 = parse_header(self.primary, self.header_off)
        header1 = parse_header(self.primary, header0.end)
        self.primary_rows = resource_entries(self.primary, header0, names, "CGMeshListResourceWin7")
        self.gpu_rows = resource_entries(self.primary, header1, names, "CGMeshListResourceWin7GPU")
        # lazy caches for material resolution (built on first use)
        self._scene_map = None
        self._material_set = None
        self._shaderset_set = None
        self._material_map = None
        self._shaderset_map = None
        self._texture_hashes = None
        self._pbr = None

    def meshlist_hashes(self) -> list[str]:
        return sorted(f"{h:016x}" for h in self.primary_rows if h in self.gpu_rows)

    # --- material resolution directly from THIS archive's loaded bytes -------

    def _ensure_maps(self) -> None:
        if self._scene_map is not None:
            return
        self._scene_map = sb.collect_type_map(self.primary, self.header_off, sb.SCENE_TYPE)
        self._material_set = sb.collect_type_set(self.primary, self.header_off, sb.MATERIAL_TYPE)
        self._shaderset_set = sb.collect_type_set(self.primary, self.header_off, sb.SHADERSET_TYPE)
        self._material_map = collect_resource_map(self.primary, self.header_off, msp.MATERIAL_TYPE)

    def binding(self, meshlist_hash: str) -> tuple[list[str], list[str]]:
        """(material_hashes[], shaderset_hashes[]) index-ordered for this meshlist.

        Parsed live from the companion CGSceneResourceWin7 (works for any archive);
        materialidx / shadersetidx select directly into these lists. ([],[]) if the
        scene binding is absent or unparseable.
        """
        self._ensure_maps()
        ent = self._scene_map.get(int(meshlist_hash, 16))
        if ent is None:
            return [], []
        pos, size = ent
        ok, _note, res = sb.parse_binding_table(
            self.primary, self.data_off + pos, size, self._material_set, self._shaderset_set)
        if not ok:
            return [], []
        return ([f"{h:016x}" for h in res["mat_hashes"]],
                [f"{h:016x}" for h in res["shd_hashes"]])

    def material_scalars_for(self, material_hash: str) -> dict:
        """decode_material_scalars for a local material; {} if not in this archive."""
        if not material_hash:
            return {}
        self._ensure_maps()
        ent = self._material_map.get(int(material_hash, 16))
        if ent is None:
            return {}
        _idx, pos, size = ent
        return msc.decode_material_scalars(self.primary[self.data_off + pos: self.data_off + pos + size])

    def _ensure_shader_scan(self) -> None:
        if self._shaderset_map is not None:
            return
        smap: dict[int, tuple[int, int]] = {}
        header = None
        for hi in range(2):
            header = parse_header(self.primary, self.header_off if hi == 0 else header.end)
            for i in range(header.contents.count):
                th, nh, val = struct.unpack_from("<QQQ", self.primary, header.contents.off + i * 24)
                if th == sts.SHADERSET_TYPE and val < header.entries.count:
                    smap[nh] = entry_at(self.primary, header, val)
        self._shaderset_map = smap
        # Archive-local textures alone are NOT a sufficient needle set: shadersets
        # overwhelmingly bind textures homed in other archives (88/115 external on
        # 0703fd2acd5803e9; 31/31 on 4a405738bee7a74b). Union with the corpus-wide
        # index so cross-archive binds are seen at all. Keeping the union rather
        # than replacing preserves any local texture missing from the index.
        # ⛔ Dropping the gate entirely was measured and rejected: 1,884 bindings,
        # 89 % false positives — struct validation alone is not selective enough.
        self._texture_hashes = sts.collect_type_hashes(
            self.primary, self.data_off, self.header_off, sts.TEXTURE_TYPE)
        self._texture_hashes |= set(load_global_texture_index())
        self._pbr = sts.build_pbr_hash_table(self.names)

    def shaderset_roles_direct(self, shaderset_hash: str) -> dict[str, str]:
        """{role_key -> tex_hash} scanned live from this archive's shaderset slices.

        Cross-archive: the needle set is this archive's textures UNIONED with the
        corpus-wide texture index, so a shaderset binding a texture that lives in
        another archive still resolves. Measured on 0703fd2acd5803e9: 60 bindings
        with local needles vs **212** with global ones, exactly reproducing the
        precomputed scan TSV.
        """
        if not shaderset_hash:
            return {}
        self._ensure_shader_scan()
        ent = self._shaderset_map.get(int(shaderset_hash, 16))
        if ent is None:
            return {}
        pos, size = ent
        rows = sts.scan_shaderset_slice(
            self.primary, self.data_off + pos, size, self.hash, shaderset_hash,
            self._texture_hashes, self.names, self._pbr)
        return mat.roles_from_input_rows(rows, self.names)

    def build(self, meshlist_hash: str) -> list[ml.MeshObject]:
        mi = int(meshlist_hash, 16)
        if mi not in self.primary_rows or mi not in self.gpu_rows:
            raise KeyError(f"{meshlist_hash} not a paired CGMeshListResource in {self.hash}")
        _pe, pos, _size = self.primary_rows[mi]
        _ge, gpu_pos, gpu_size = self.gpu_rows[mi]
        start = self.data_off + pos
        # Empty mesh-list resource: all eight loader-order table counts are 0
        # (48-byte all-zero primary, gpudatasize 0, paired to a 16-byte GPU stub).
        # These are legitimately empty (the recorded baseline excludes them too;
        # 106 exist corpus-wide) — return no objects rather than a false FAIL.
        if not any(struct.unpack_from("<8I", self.primary, start)):
            return []
        parsed = parse_candidate(self.primary, start, gpu_size)
        if parsed is None:
            raise RuntimeError(f"parse_candidate failed for {meshlist_hash}")

        def tbl(name):
            t = parsed[name]
            return ml.Table(t.count, t.data_off)

        return ml.build_objects(
            self.primary, self.gpu, gpu_pos,
            meshes=tbl("meshes"), renderparams=tbl("renderparams"),
            vertexbuffers=tbl("vertexbuffers"), indexbuffers=tbl("indexbuffers"),
            # populated in only 11 of the corpus's 1,240 mesh-lists, but where it
            # IS populated the coarser LODs are extra draws over later slices of
            # the same index buffer — import them all and the levels overlap.
            lodchildindices=tbl("lodchildindices"),
        )


def _material_key(si: int, shd_hash: str, mat_hash: str) -> str:
    if shd_hash and mat_hash:
        return f"{shd_hash}__{mat_hash}"
    if shd_hash:
        return shd_hash
    if mat_hash:
        return mat_hash
    return f"shd{si}"


def _resolve_materials(arc: "Archive", meshlist_hash: str, objects: list[ml.MeshObject],
                       *, out_dir: Path, shd_tex: dict, dxgi: dict, tex_home: dict,
                       names: dict, direct: bool = False, want_textures: bool = False,
                       verbose: bool = False) -> list[dict]:
    """Resolve per-draw materials into unique specs.

    Binds each draw's shadersetidx/materialidx -> shaderset+material hash, resolves
    texture roles (from the archive live when `direct`, else the scan TSV), decodes
    SGMaterialData scalars, optionally extracts the referenced DDS into
    `<out_dir>/textures/`, and stamps each draw's material_key.
    """
    mats, shds = arc.binding(meshlist_hash)

    # --- per-draw hash assignment ---
    pairs: dict[str, tuple[str, str]] = {}
    for obj in objects:
        for draw in obj.draws:
            si, midx = draw.shaderset_index, draw.material_index
            shd_hash = shds[si] if 0 <= si < len(shds) else ""
            mat_hash = mats[midx] if 0 <= midx < len(mats) else ""
            key = _material_key(si, shd_hash, mat_hash)
            draw.material_key = key
            pairs.setdefault(key, (shd_hash, mat_hash))

    # --- role textures per unique material key ---
    role_by_key: dict[str, dict[str, str]] = {}
    dxgi_local = dict(dxgi)                 # merge real extracted formats into a copy
    needed_tex: dict[str, str] = {}        # tex_hash -> home archive
    for key, (shd_hash, mat_hash) in pairs.items():
        roles = arc.shaderset_roles_direct(shd_hash) if direct else dict(shd_tex.get(shd_hash, {}))
        role_by_key[key] = roles
        for tex_hash in roles.values():
            # Never assume the texture is local. `le_textures.extract_by_hashes`
            # silently skips a hash that is not in the archive it is handed, so
            # assuming `arc.hash` in direct mode made DDS extraction a no-op for
            # 88/115 of the reference archive's textures and 31/31 of
            # 4a405738bee7a74b's.
            home = tex_home.get(tex_hash, arc.hash)
            needed_tex.setdefault(tex_hash, home)

    # --- texture extraction (grouped by home archive) ---
    texture_files: dict[str, str] = {}
    if want_textures and needed_tex:
        textures_dir = Path(out_dir) / "textures"
        by_home: dict[str, set[str]] = {}
        for tex_hash, home in needed_tex.items():
            by_home.setdefault(home, set()).add(tex_hash)
        for home, hashes in sorted(by_home.items()):
            meta = le_textures.extract_by_hashes(home, hashes, textures_dir, verbose=verbose)
            for tex_hash, m in meta.items():
                texture_files[tex_hash] = f"textures/{tex_hash}.dds"
                if m.get("dxgi_format"):
                    dxgi_local[tex_hash] = int(m["dxgi_format"])

    # --- material scalars, local first then cross-archive -------------------
    # Only ~19 % of bound materials are resident in the binding archive. A miss
    # here is SILENT: the spec falls back to SGMaterialData defaults, so an
    # eMTForwardTransparent material reads as mattype 0 / eBlendOpaque and
    # renders opaque. Resolve the rest from their home archive.
    scalars_by_hash: dict[str, dict] = {}
    unresolved: dict[str, str] = {}
    mat_index = load_global_material_index()
    for _key, (_shd, mat_hash) in pairs.items():
        if not mat_hash or mat_hash in scalars_by_hash or mat_hash in unresolved:
            continue
        local = arc.material_scalars_for(mat_hash)
        if local:
            scalars_by_hash[mat_hash] = local
        else:
            home = mat_index.get(mat_hash.lower())
            if home and home != arc.hash:
                unresolved[mat_hash] = home
    if unresolved:
        found = foreign_material_scalars(unresolved, verbose=verbose)
        scalars_by_hash.update(found)
        if verbose or len(found) < len(unresolved):
            print(f"    material scalars: {len(scalars_by_hash)} resolved "
                  f"({len(found)}/{len(unresolved)} cross-archive)")

    # --- build the specs ---
    specs: dict[str, dict] = {}
    for key, (shd_hash, mat_hash) in pairs.items():
        specs[key] = mat.build_material_spec(
            key, shaderset_hash=shd_hash, material_hash=mat_hash,
            role_textures=role_by_key.get(key, {}), dxgi_by_tex=dxgi_local,
            scalars=scalars_by_hash.get(mat_hash, {}), texture_files=texture_files)
    return list(specs.values())


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--archive", default="0703fd2acd5803e9", help="archive name hash")
    ap.add_argument("--mesh", action="append", default=[], help="meshlist hash (repeatable)")
    ap.add_argument("--all", action="store_true", help="extract every meshlist in the archive")
    ap.add_argument("--list", action="store_true", help="list meshlist hashes and exit")
    ap.add_argument("--out", type=Path, default=BLENDER_TOOL / "exports",
                    help="output root for .lemesh packages")
    ap.add_argument("--no-materials", action="store_true", help="skip M2 material resolution")
    ap.add_argument("--textures", action="store_true",
                    help="extract referenced DDS textures into <pkg>/textures/ (incl. cross-archive homes)")
    ap.add_argument("--tsv-materials", action="store_true",
                    help="resolve shaderset->texture from precomputed scan TSVs under "
                         "$LONE_ECHO_SCAN_ROOT instead of live from the archive. "
                         "LEGACY: the TSVs only cover the archives you scanned")
    ap.add_argument("--direct-materials", action="store_true",
                    help=argparse.SUPPRESS)   # deprecated: direct is now the default
    ap.add_argument("--drop-shadow-only", action="store_true",
                    help="omit eShadowOnly meshes from the package")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    names = load_hash_lookup(DEFAULT_HASH_LOOKUP)
    print(f"hash_lookup: {len(names)} entries")
    print(f"loading archive {args.archive} ...")
    arc = Archive(args.archive, names)
    all_hashes = arc.meshlist_hashes()
    print(f"  {len(all_hashes)} paired CGMeshListResource(s)")

    if args.list:
        for h in all_hashes:
            print(f"  {h}")
        return 0

    # M2 inputs. Direct (live-from-archive) resolution is the DEFAULT: measured
    # on the reference archive it reproduces a precomputed scan TSV exactly (212
    # bindings / 57 shadersets both ways) and, unlike a TSV, it works on every
    # archive without a prior scan. `--direct-materials` is retained as a no-op
    # alias so old invocations keep working.
    direct = not args.tsv_materials
    shd_tex = dxgi = tex_home = {}
    if not args.no_materials:
        warn_missing_indexes()
        if not direct and SCAN_TSV.exists():
            shd_tex = mat.load_shaderset_textures(SCAN_TSV, names)
        # dxgi + homes are needed in BOTH modes: direct resolution still has to know
        # which archive to pull each DDS out of, and what format it is.
        dxgi = mat.load_dxgi_by_tex(*TEX_MANIFESTS)
        tex_home = mat.load_texture_homes(SCAN_TSV if SCAN_TSV.exists() else None,
                                          *TEX_MANIFESTS)
        for th, home in load_global_texture_index().items():
            tex_home.setdefault(f"{th:016x}", home)
        src = "direct-from-archive" if direct else f"{len(shd_tex)} shadersets (TSV)"
        print(f"  materials: {src}, {len(dxgi)} texture formats, "
              f"{len(tex_home)} texture homes")

    targets = all_hashes if args.all else [h.lower() for h in args.mesh]
    if not targets:
        ap.error("nothing to do: pass --mesh <hash> (repeatable), --all, or --list")

    ok = fail = skip = 0
    for h in targets:
        try:
            objects = arc.build(h)
            if not objects:
                print(f"  SKIP {h}: empty mesh-list (no geometry)")
                skip += 1
                continue
            out_dir = args.out / f"{args.archive}_{h}.lemesh"
            materials = ([] if args.no_materials else
                         _resolve_materials(arc, h, objects, out_dir=out_dir,
                                            shd_tex=shd_tex, dxgi=dxgi, tex_home=tex_home,
                                            names=names, direct=direct,
                                            want_textures=args.textures, verbose=args.verbose))
            pkg.write_package(
                out_dir,
                source={"game": "lone_echo", "archive": args.archive, "meshlist": h,
                        "tool_version": "0.1.0"},
                objects=objects, materials=materials,
                drop_shadow_only=args.drop_shadow_only,
            )
            nverts = sum(o.vertex_count for o in objects)
            ntris = sum(sum(d.idx_count for d in o.draws if d.is_triangles) // 3
                        for o in objects)
            print(f"  OK  {h}: {len(objects)} meshes, {nverts} verts, {ntris} tris, "
                  f"{len(materials)} materials -> {out_dir.name}")
            ok += 1
        except Exception as exc:   # noqa: BLE001
            print(f"  FAIL {h}: {exc}")
            if args.verbose:
                import traceback
                traceback.print_exc()
            fail += 1

    print(f"\ndone: {ok} extracted, {skip} skipped (empty), {fail} failed -> {args.out}")
    return 1 if fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
