"""The LEVEL material sidecar `<master>_materials.json` — schema v2.

Pure stdlib: no `bpy`, no Oodle, no archive load. Two halves:

  * SYNTHETIC — a hand-built v2 envelope and a hand-built v1 envelope, so the
    contract is locked deterministically even in a fresh clone (the real
    artifacts live under `blender_tool/exports/`, which is NOT tracked by git).
  * REAL — the same invariants re-run against
    `blender_tool/exports/942c829457a04a62_materials.json` (station_front, 1050
    meshes / 21394 instances) when it is present, plus the station_front-specific
    floors. Absent file => every test in that half raises `unittest.SkipTest`
    with a reason naming the artifact, never a silent PASS of the synthetic
    half.

WHY THIS FILE EXISTS
--------------------
The single-mesh `.lemesh` path carries a 35-field material spec (alpha /
render_mode, emissive layer+tint+intensity, specular, roughness_is_sqrt,
ao_channel, layer blends, mattype/blendmode, flags, named scalars, and a
`channels` dict of resolved texture roles). The level path emitted 11 flat
fields and 2 texture channels — a whole generation behind, so none of the
alpha / emissive / specular / roughness / blend-mask / AO / colorspace /
alpha_mode work reached a level render. v2 carries the spec VERBATIM: the
consumer calls `material_builder.build_material(spec, tex_base, opts)` with
zero adaptation, and this file is what stops it drifting again.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from unittest import SkipTest

HERE = Path(__file__).resolve().parent
BLENDER_TOOL = HERE.parent
LE_ROOT = BLENDER_TOOL.parent
for _p in (str(BLENDER_TOOL), str(LE_ROOT / "scripts")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from le_mesh import materials as M  # noqa: E402


# ---------------------------------------------------------------------------
# the pinned contract
# ---------------------------------------------------------------------------

#: exact top-level envelope of a v2 sidecar.
V2_ENVELOPE_KEYS = {"version", "master", "textures_subdir", "materials"}
SIDECAR_VERSION = 2

#: exactly the 11 flat fields a v1 sidecar carried (and NO "version" key).
V1_FIELDS = {"matidx", "shdidx", "material_hash", "mattype", "base_color",
             "basecolor_texture", "basecolor_dds", "basecolor_role",
             "normal_texture", "owning_archive", "double_sided"}

#: every spec key `addon/lone_echo_import/material_builder.build_material` (and
#: its helpers) reads. A v2 `spec` that is missing any of these cannot be handed
#: to the builder unadapted, which is the entire point of v2.
BUILDER_SPEC_KEYS = (
    "key", "shaderset_hash", "material_hash",
    "channels", "role_textures", "layers", "primary_layer", "unrouted_roles",
    "double_sided", "base_color_factor",
    "alpha", "alpha_source", "alpha_terms", "alpha_blend_lossy",
    "alpha_threshold", "alpha_threshold_default",
    "render_mode", "mattype", "mattype_name", "blend_mode", "blend_mode_name",
    "emissive_color", "emissive_intensity", "emissive_layer", "emissive_scale",
    "emissive_tint", "ior", "roughness_is_sqrt", "ao_channel",
    "layer_blend_suppressed",
)

#: keys every resolved texture channel must carry for the image node to be built
#: correctly (colorspace, BC5 Z-reconstruct, and the alpha_mode fix documented
#: §3b — Blender's default STRAIGHT silently corrupts a channel-packed albedo).
CHANNEL_KEYS = ("texture", "role_key", "dxgi", "colorspace", "reconstruct_z",
                "confidence", "layer", "alpha_mode", "alpha_is_linear", "file")

#: the (mattype, blendmode) pairings the shipped corpus actually uses. A garbage
#: material slice — which is exactly what a SILENT cross-archive miss produces —
#: scatters across impossible combinations, so coherence is the cheap proof that
#: resolution landed on real bytes.
COHERENT_PAIRS = {
    ("eMTAlphaTested", "eBlendOpaque"),
    ("eMTSkirt", "eBlendSkirt"),
    ("eMTForwardOpaque", "eBlendOpaque"),
    ("eMTDeferredOpaque", "eBlendOpaque"),
    ("eMTForwardTransparent", "eBlendTranslucent"),
    ("eMTForwardTransparent", "eBlendTransparent"),
    ("eMTTransparentPostAA", "eBlendTranslucent"),
    ("eMTTransparentPostAA", "eBlendTransparent"),
}

#: station_front sidecar, regenerated by
#:   python.exe scripts/le_scene_materials.py 942c829457a04a62 \
#:     --manifest blender_tool/exports/942c829457a04a62.lescatter/manifest.json \
#:     --out-textures blender_tool/exports/942c829457a04a62_textures \
#:     --out-json     blender_tool/exports/942c829457a04a62_materials.json
REAL_SIDECAR = BLENDER_TOOL / "exports" / "942c829457a04a62_materials.json"
REAL_MASTER = "942c829457a04a62"
#: the v1 sidecar had exactly 67 (matidx, shdidx) pairs and 2 channels
#: (base_color, normal). v2 must not LOSE pairs, and must not lose base_color.
REAL_MIN_PAIRS = 67
REAL_MIN_BASE_COLOR = 60
REAL_MIN_NORMAL = 60


# ---------------------------------------------------------------------------
# synthetic fixtures
# ---------------------------------------------------------------------------

def _channel(tex: str, role: str, dxgi: int, subdir: str = "T") -> dict:
    """A channel exactly as `le_mesh.materials._channel` + build_material_spec
    emit it — built through the real module so the fixture cannot drift from the
    producer."""
    ch = dict(M._channel(role, tex, {tex: dxgi}))
    ch["file"] = f"{subdir}/{tex}.dds"
    return ch


def _spec(key="shd__mat", *, role_textures=None, dxgi=None, scalars=None,
          subdir="T") -> dict:
    """A spec built by THE producer (`build_material_spec`) — same call the
    extractor makes — so this file tests the contract, not a copy of it."""
    role_textures = role_textures or {}
    dxgi = dxgi or {}
    shd, _, mat_hash = key.partition("__")
    return M.build_material_spec(
        key, shaderset_hash=shd, material_hash=mat_hash,
        role_textures=role_textures, dxgi_by_tex=dxgi, scalars=scalars or {},
        texture_files={t: f"{subdir}/{t}.dds" for t in role_textures.values()})


def _synthetic_v2() -> dict:
    """A two-entry v2 envelope covering an opaque and an alpha-tested material."""
    roles_a = {
        "layer0_composite_diffuse": "aa00000000000001",
        "layer0_composite_normals": "aa00000000000002",
        "layer0_composite_components": "aa00000000000003",
        "layer0_composite_specular": "aa00000000000004",
        "layer1_emissive_map": "aa00000000000005",
        "layer1_blend_mask": "aa00000000000006",
        "layer0_opacity_map": "aa00000000000007",
    }
    dxgi_a = {"aa00000000000001": 78, "aa00000000000002": 83,
              "aa00000000000003": 80, "aa00000000000004": 78,
              "aa00000000000005": 72, "aa00000000000006": 80,
              "aa00000000000007": 72}
    scalars_a = {
        "mattype": 9, "mattype_name": "eMTAlphaTested",
        "blend_mode": 0, "blend_mode_name": "eBlendOpaque",
        "flags": 30, "flag_names": ["eCastShadows"], "materialfx": "",
        "is_emissive": True, "named_scalars": {}, "named_scalars_resolved": {},
        "base_color_factor": [0.5, 0.5, 0.5, 1.0],
        "emissive_color": [0.0, 0.0, 0.0], "emissive_intensity": 1.0,
        "alpha": 1.0, "double_sided": True,
        "layers": [{"index": 0}, {"index": 1, "emissive_intensity": 25.0,
                                  "emissive_tint": [1.0, 0.6, 0.2]}],
    }
    scalars_b = {
        "mattype": 10, "mattype_name": "eMTSkirt",
        "blend_mode": 10, "blend_mode_name": "eBlendSkirt",
        "flags": 2, "flag_names": [], "materialfx": "",
        "is_emissive": False, "named_scalars": {}, "named_scalars_resolved": {},
        "base_color_factor": [1.0, 1.0, 1.0, 1.0],
        "emissive_color": [0.0, 0.0, 0.0], "emissive_intensity": 1.0,
        "alpha": 1.0, "double_sided": False, "layers": [],
    }
    return {
        "version": SIDECAR_VERSION,
        "master": "942c829457a04a62",
        "textures_subdir": "T",
        "materials": [
            {"matidx": 3, "shdidx": 5,
             "spec": _spec("s1__m1", role_textures=roles_a, dxgi=dxgi_a,
                           scalars=scalars_a)},
            {"matidx": 4, "shdidx": 6,
             "spec": _spec("s2__m2", scalars=scalars_b)},
        ],
    }


def _synthetic_v1() -> dict:
    return {
        "master": "942c829457a04a62",
        "materials": [{
            "matidx": 3, "shdidx": 5, "material_hash": "814b9214074ca852",
            "mattype": 9, "base_color": [0.17, 0.09, 0.02],
            "basecolor_texture": "49015a02197ef1fc",
            "basecolor_dds": "942c829457a04a62_textures/49015a02197ef1fc.dds",
            "basecolor_role": "layer0_composite_diffuse",
            "normal_texture": "852efbf1c22b6a4e",
            "owning_archive": "88e3475bb562f454", "double_sided": True,
        }],
    }


# ---------------------------------------------------------------------------
# the reusable invariant battery (run on synthetic AND real data)
# ---------------------------------------------------------------------------

def _check_v2_envelope(doc: dict, label: str) -> None:
    assert set(doc) == V2_ENVELOPE_KEYS, f"{label}: envelope keys {sorted(doc)}"
    assert doc["version"] == SIDECAR_VERSION, f"{label}: version {doc['version']}"
    assert isinstance(doc["master"], str) and len(doc["master"]) == 16, label
    assert isinstance(doc["textures_subdir"], str) and doc["textures_subdir"], label
    assert isinstance(doc["materials"], list) and doc["materials"], label
    for entry in doc["materials"]:
        assert set(entry) == {"matidx", "shdidx", "spec"}, f"{label}: {sorted(entry)}"
        assert isinstance(entry["matidx"], int) and isinstance(entry["shdidx"], int)
        assert isinstance(entry["spec"], dict)


def _check_specs_are_builder_ready(doc: dict, label: str) -> None:
    subdir = doc["textures_subdir"]
    for entry in doc["materials"]:
        spec = entry["spec"]
        missing = [k for k in BUILDER_SPEC_KEYS if k not in spec]
        assert not missing, f"{label}: spec {spec.get('key')} missing {missing}"
        # key format is le_extract.material_key's: "<shaderset>__<material>"
        if spec["shaderset_hash"] and spec["material_hash"]:
            assert spec["key"] == f"{spec['shaderset_hash']}__{spec['material_hash']}", label
        assert isinstance(spec["channels"], dict)
        assert isinstance(spec["layers"], list)
        assert spec["render_mode"] in (M.RENDER_MODE_OPAQUE, M.RENDER_MODE_CLIP,
                                       M.RENDER_MODE_BLEND), label
        for name, ch in spec["channels"].items():
            for k in CHANNEL_KEYS:
                assert k in ch, f"{label}: channel {name} missing {k}"
            # paths are SIDECAR-relative, mirroring .lemesh's textures/ subdir
            assert ch["file"] == "" or ch["file"].startswith(subdir + "/"), \
                f"{label}: channel {name} file {ch['file']!r} not under {subdir}/"
            assert ch["colorspace"] in ("sRGB", "Non-Color"), label
            assert ch["alpha_mode"] in (M.ALPHA_MODE_CHANNEL_PACKED,
                                        M.ALPHA_MODE_STRAIGHT,
                                        M.ALPHA_MODE_NONE), label
            assert ch["alpha_is_linear"] is True, label


def _check_role_names_are_real(doc: dict, label: str) -> None:
    """⛔ Ten role names were fabricated once. Every routed role_key must be a
    cracked `INPUTNAME_ROLE` name (or an explicit `unknown_s{slot}` placeholder)
    — never an invented one."""
    for entry in doc["materials"]:
        for name, ch in entry["spec"]["channels"].items():
            rk = ch["role_key"]
            assert rk in M.KNOWN_ROLES or rk.startswith("unknown_s"), \
                f"{label}: fabricated role name {rk!r} on channel {name}"


def _check_coherence(doc: dict, label: str) -> tuple[int, int]:
    bad = []
    for entry in doc["materials"]:
        spec = entry["spec"]
        pair = (spec.get("mattype_name") or "", spec.get("blend_mode_name") or "")
        # a name pair must at minimum be self-consistent with the numeric fields
        assert M.MATTYPE_NAMES.get(int(spec["mattype"]), "") == pair[0], label
        assert M.BLENDMODE_NAMES.get(int(spec["blend_mode"]), "") == pair[1], label
        if pair not in COHERENT_PAIRS:
            bad.append((spec.get("key"), pair))
    return len(doc["materials"]) - len(bad), len(doc["materials"])


def _channel_histogram(doc: dict) -> dict:
    hist: dict = {}
    for entry in doc["materials"]:
        for name in entry["spec"]["channels"]:
            hist[name] = hist.get(name, 0) + 1
    return hist


def _load_real() -> dict | None:
    """The real station_front sidecar, or None when it is absent / not v2.

    `blender_tool/exports/` is not tracked by git, so a fresh clone legitimately
    has no artifact and the REAL half becomes a no-op. A file that IS present but
    is not v2 is a REGRESSION, not an absence — `test_real_sidecar_is_v2` fails
    loudly on it, and the remaining real tests stay quiet so one root cause does
    not print as five failures.
    """
    if not REAL_SIDECAR.exists():
        return None
    doc = json.loads(REAL_SIDECAR.read_text(encoding="utf-8"))
    return doc if doc.get("version") == SIDECAR_VERSION else None


def test_real_sidecar_is_v2():
    """A sidecar on disk must be v2 — a v1 file means the artifact is stale."""
    if not REAL_SIDECAR.exists():
        raise SkipTest(
            f"{REAL_SIDECAR.name} is absent — `blender_tool/exports/` is "
            f"gitignored extracted game data, so a clean checkout has none. "
            f"Write it with `python.exe scripts/le_scene_materials.py "
            f"{REAL_MASTER} --manifest blender_tool/exports/{REAL_MASTER}"
            f".lescatter/manifest.json --out-textures blender_tool/exports/"
            f"{REAL_MASTER}_textures --out-json {REAL_SIDECAR}` to make this "
            f"test able to run. ⛔ WHILE THIS SKIP IS ACTIVE NOTHING DETECTS A "
            f"STALE v1 LEVEL MATERIAL SIDECAR ON DISK.")
    doc = json.loads(REAL_SIDECAR.read_text(encoding="utf-8"))
    assert doc.get("version") == SIDECAR_VERSION, (
        f"{REAL_SIDECAR.name} is schema v{doc.get('version', 1)}, expected v2 — "
        "regenerate with scripts/le_scene_materials.py")


# ---------------------------------------------------------------------------
# SYNTHETIC — always run
# ---------------------------------------------------------------------------

def test_v2_envelope_is_exactly_the_pinned_shape():
    _check_v2_envelope(_synthetic_v2(), "synthetic")


def test_every_spec_carries_the_keys_build_material_reads():
    _check_specs_are_builder_ready(_synthetic_v2(), "synthetic")


def test_spec_is_the_same_dict_shape_as_a_lemesh_manifest_entry():
    """v2's `spec` must be produced by THE producer, not a level-specific copy.

    Assert key-for-key equality against a directly-built `build_material_spec`
    result: any level-side renaming/subsetting shows up here immediately.
    """
    doc = _synthetic_v2()
    spec = doc["materials"][1]["spec"]
    reference = M.build_material_spec(
        "s2__m2", shaderset_hash="s2", material_hash="m2",
        role_textures={}, dxgi_by_tex={},
        scalars={"mattype": 10, "mattype_name": "eMTSkirt", "blend_mode": 10,
                 "blend_mode_name": "eBlendSkirt", "flags": 2, "flag_names": [],
                 "materialfx": "", "is_emissive": False, "named_scalars": {},
                 "named_scalars_resolved": {},
                 "base_color_factor": [1.0, 1.0, 1.0, 1.0],
                 "emissive_color": [0.0, 0.0, 0.0], "emissive_intensity": 1.0,
                 "alpha": 1.0, "double_sided": False, "layers": []},
        texture_files={})
    assert set(spec) == set(reference), (
        f"level spec keys diverged: only-level={sorted(set(spec) - set(reference))} "
        f"only-lemesh={sorted(set(reference) - set(spec))}")


def test_channels_carry_the_full_texture_contract():
    doc = _synthetic_v2()
    chans = doc["materials"][0]["spec"]["channels"]
    # the seven bound roles must route to distinct Principled-facing channels,
    # not collapse to base_color+normal the way v1 did
    for name in ("base_color", "normal", "roughness", "specular", "emission",
                 "blend_mask", "transmission"):
        assert name in chans, f"{name} not routed"
    assert chans["base_color"]["colorspace"] == "sRGB"        # DXGI 78 == BC3_SRGB
    assert chans["normal"]["colorspace"] == "Non-Color"
    assert chans["normal"]["reconstruct_z"] is True           # DXGI 83 == BC5
    assert chans["roughness"]["roughness_is_sqrt"] is True
    assert chans["roughness"]["ao_channel"] == "G"
    # a channel-packed albedo must NOT be un-premultiplied on load
    assert chans["base_color"]["alpha_mode"] == M.ALPHA_MODE_CHANNEL_PACKED
    assert chans["normal"]["alpha_mode"] == M.ALPHA_MODE_NONE


def test_emissive_uses_the_layer_that_actually_carries_the_map():
    """The layer-selection bug (layer0 wins unconditionally) was 12.5x too dim."""
    spec = _synthetic_v2()["materials"][0]["spec"]
    assert spec["emissive_layer"] == 1
    assert spec["emissive_intensity"] == 25.0
    assert spec["emissive_tint"] == [1.0, 0.6, 0.2]


def test_role_names_are_never_fabricated():
    _check_role_names_are_real(_synthetic_v2(), "synthetic")


def test_mattype_blendmode_pairing_is_coherent_synthetic():
    ok, total = _check_coherence(_synthetic_v2(), "synthetic")
    assert ok == total == 2


def test_incoherent_pairing_is_actually_detected():
    """The coherence check must be able to FAIL — otherwise it proves nothing."""
    doc = _synthetic_v2()
    doc["materials"][0]["spec"]["mattype"] = 10          # eMTSkirt ...
    doc["materials"][0]["spec"]["mattype_name"] = "eMTSkirt"
    doc["materials"][0]["spec"]["blend_mode"] = 0        # ... with eBlendOpaque
    doc["materials"][0]["spec"]["blend_mode_name"] = "eBlendOpaque"
    ok, total = _check_coherence(doc, "synthetic-broken")
    assert ok == 1 and total == 2


def test_v1_sidecar_still_parses():
    """Back-compat: a v1 sidecar has NO "version" key and the 11 flat fields."""
    doc = _synthetic_v1()
    assert "version" not in doc
    assert set(doc) == {"master", "materials"}
    for entry in doc["materials"]:
        assert set(entry) == V1_FIELDS, sorted(entry)
    # and the discriminator a consumer uses is exactly the "version" key
    assert doc.get("version", 1) == 1
    assert _synthetic_v2().get("version", 1) == 2


def test_v1_projection_matches_the_v2_spec_it_came_from():
    """`_v1_entry` must be a projection, so v1 and v2 can never disagree."""
    from unittest import SkipTest                      # noqa: PLC0415
    try:
        from le_scene_materials import _v1_entry       # noqa: PLC0415
    except ImportError as exc:                         # pragma: no cover
        # `scripts/le_scene_materials.py` pulls in the Oodle-backed decode stack
        # at import time, which a checkout without `pyoodle` cannot satisfy.
        raise SkipTest(
            f"scripts/le_scene_materials.py is not importable here ({exc}). "
            "`pip install pyoodle` (or check it out beside this repository) to "
            "enable it. ⛔ WHILE THIS SKIP IS ACTIVE THE v1 SIDECAR PROJECTION "
            "IS UNVERIFIED.")

    doc = _synthetic_v2()
    entry = doc["materials"][0]
    v1 = _v1_entry(entry, {"aa00000000000001": ["deadbeefdeadbeef", 0, 0, 0]})
    assert set(v1) == V1_FIELDS
    spec = entry["spec"]
    assert v1["mattype"] == spec["mattype"]
    assert v1["double_sided"] == spec["double_sided"]
    assert v1["basecolor_texture"] == spec["channels"]["base_color"]["texture"]
    assert v1["basecolor_role"] == spec["channels"]["base_color"]["role_key"]
    assert v1["basecolor_dds"] == spec["channels"]["base_color"]["file"]
    assert v1["normal_texture"] == spec["channels"]["normal"]["texture"]
    assert v1["owning_archive"] == "deadbeefdeadbeef"


def test_channel_count_floor_synthetic():
    hist = _channel_histogram(_synthetic_v2())
    # v1 could only ever emit two roles; v2 must beat that on a real material
    assert len([c for c in hist if hist[c]]) >= 7, hist


# ---------------------------------------------------------------------------
# REAL — station_front, when the artifact is on disk
# ---------------------------------------------------------------------------

def test_real_sidecar_envelope_and_specs():
    doc = _load_real()
    if doc is None:
        raise SkipTest(
            f"{REAL_SIDECAR.name} is absent, or is on disk but not schema v2 "
            f"(`test_real_sidecar_is_v2` is the loud check for the stale "
            f"case) — `blender_tool/exports/` is gitignored extracted game "
            f"data. Write it with `python.exe scripts/le_scene_materials.py "
            f"{REAL_MASTER} --manifest blender_tool/exports/{REAL_MASTER}"
            f".lescatter/manifest.json --out-textures blender_tool/exports/"
            f"{REAL_MASTER}_textures --out-json {REAL_SIDECAR}` to make this "
            f"test able to run. ⛔ WHILE THIS SKIP "
            f"IS ACTIVE NOTHING CHECKS THAT A REAL v2 SIDECAR'S ENVELOPE AND "
            f"SPECS ARE BUILDER-READY.")
    _check_v2_envelope(doc, "station_front")
    _check_specs_are_builder_ready(doc, "station_front")
    _check_role_names_are_real(doc, "station_front")
    assert doc["master"] == REAL_MASTER
    assert doc["textures_subdir"] == f"{REAL_MASTER}_textures"


def test_real_sidecar_keeps_every_v1_pair():
    doc = _load_real()
    if doc is None:
        raise SkipTest(
            f"{REAL_SIDECAR.name} is absent, or is on disk but not schema v2 "
            f"(`test_real_sidecar_is_v2` is the loud check for the stale "
            f"case) — `blender_tool/exports/` is gitignored extracted game "
            f"data. Write it with `python.exe scripts/le_scene_materials.py "
            f"{REAL_MASTER} --manifest blender_tool/exports/{REAL_MASTER}"
            f".lescatter/manifest.json --out-textures blender_tool/exports/"
            f"{REAL_MASTER}_textures --out-json {REAL_SIDECAR}` to make this "
            f"test able to run. ⛔ WHILE THIS SKIP "
            f"IS ACTIVE NOTHING CHECKS THAT v2 KEPT EVERY (matidx, shdidx) "
            f"PAIR v1 CARRIED, ONCE EACH.")
    assert len(doc["materials"]) >= REAL_MIN_PAIRS, len(doc["materials"])
    pairs = {(e["matidx"], e["shdidx"]) for e in doc["materials"]}
    assert len(pairs) == len(doc["materials"]), "duplicate (matidx, shdidx)"


def test_real_sidecar_channel_floor():
    """v1 resolved 2 channels. v2 must keep base_color/normal and add more."""
    doc = _load_real()
    if doc is None:
        raise SkipTest(
            f"{REAL_SIDECAR.name} is absent, or is on disk but not schema v2 "
            f"(`test_real_sidecar_is_v2` is the loud check for the stale "
            f"case) — `blender_tool/exports/` is gitignored extracted game "
            f"data. Write it with `python.exe scripts/le_scene_materials.py "
            f"{REAL_MASTER} --manifest blender_tool/exports/{REAL_MASTER}"
            f".lescatter/manifest.json --out-textures blender_tool/exports/"
            f"{REAL_MASTER}_textures --out-json {REAL_SIDECAR}` to make this "
            f"test able to run. ⛔ WHILE THIS SKIP "
            f"IS ACTIVE NOTHING CHECKS THAT v2 KEPT base_color/normal AND "
            f"ADDED AT LEAST ONE CHANNEL v1 COULD NEVER EMIT.")
    hist = _channel_histogram(doc)
    assert hist.get("base_color", 0) >= REAL_MIN_BASE_COLOR, hist
    assert hist.get("normal", 0) >= REAL_MIN_NORMAL, hist
    # the channels that never reached the level path before v2
    new_channels = [c for c in ("roughness", "specular", "emission",
                                "blend_mask", "opacity", "transmission", "alpha")
                    if hist.get(c, 0) > 0]
    assert new_channels, f"v2 added no new channel over v1: {hist}"


def test_real_sidecar_mattype_blendmode_coherence():
    doc = _load_real()
    if doc is None:
        raise SkipTest(
            f"{REAL_SIDECAR.name} is absent, or is on disk but not schema v2 "
            f"(`test_real_sidecar_is_v2` is the loud check for the stale "
            f"case) — `blender_tool/exports/` is gitignored extracted game "
            f"data. Write it with `python.exe scripts/le_scene_materials.py "
            f"{REAL_MASTER} --manifest blender_tool/exports/{REAL_MASTER}"
            f".lescatter/manifest.json --out-textures blender_tool/exports/"
            f"{REAL_MASTER}_textures --out-json {REAL_SIDECAR}` to make this "
            f"test able to run. ⛔ WHILE THIS SKIP "
            f"IS ACTIVE NOTHING CHECKS (mattype, blendmode) COHERENCE ON A "
            f"REAL SIDECAR.")
    ok, total = _check_coherence(doc, "station_front")
    # a silent cross-archive miss produces default (mattype 0 / eBlendOpaque)
    # rows, which ARE coherent — so this is a floor on garbage, not on defaults.
    assert ok == total, f"{total - ok}/{total} incoherent (mattype, blendmode) pairs"


def test_real_sidecar_texture_files_exist():
    doc = _load_real()
    if doc is None:
        raise SkipTest(
            f"{REAL_SIDECAR.name} is absent, or is on disk but not schema v2 "
            f"(`test_real_sidecar_is_v2` is the loud check for the stale "
            f"case) — `blender_tool/exports/` is gitignored extracted game "
            f"data. Write it (and its DDS files) with `python.exe "
            f"scripts/le_scene_materials.py {REAL_MASTER} --manifest "
            f"blender_tool/exports/{REAL_MASTER}.lescatter/manifest.json "
            f"--out-textures blender_tool/exports/{REAL_MASTER}_textures "
            f"--out-json {REAL_SIDECAR}` to make this test able to run. ⛔ "
            f"WHILE THIS SKIP IS ACTIVE NOTHING CHECKS THAT EVERY CHANNEL DDS "
            f"A REAL SIDECAR NAMES IS ACTUALLY ON DISK BESIDE IT.")
    base = REAL_SIDECAR.parent
    missing = []
    for entry in doc["materials"]:
        for name, ch in entry["spec"]["channels"].items():
            if ch["file"] and not (base / ch["file"]).exists():
                missing.append(ch["file"])
    assert not missing, f"{len(missing)} channel file(s) absent, e.g. {missing[:3]}"


def test_real_sidecar_scalars_came_off_disk():
    """`build_material_spec` only copies `flags`/`named_scalars` into the spec
    when a material slice was actually decoded — so their presence is the tell
    that cross-archive material resolution landed (finding O1: only ~19% of
    bound materials are resident in the binding archive, and a miss is SILENT)."""
    doc = _load_real()
    if doc is None:
        raise SkipTest(
            f"{REAL_SIDECAR.name} is absent, or is on disk but not schema v2 "
            f"(`test_real_sidecar_is_v2` is the loud check for the stale "
            f"case) — `blender_tool/exports/` is gitignored extracted game "
            f"data. Write it with `python.exe scripts/le_scene_materials.py "
            f"{REAL_MASTER} --manifest blender_tool/exports/{REAL_MASTER}"
            f".lescatter/manifest.json --out-textures blender_tool/exports/"
            f"{REAL_MASTER}_textures --out-json {REAL_SIDECAR}` to make this "
            f"test able to run. ⛔ WHILE THIS SKIP IS ACTIVE NOTHING CHECKS "
            f"THAT CROSS-ARCHIVE MATERIAL RESOLUTION LANDED — AND PER FINDING "
            f"O1 A MISS IS SILENT, LEAVING DEFAULT SCALARS THAT LOOK VALID.")
    with_scalars = sum(1 for e in doc["materials"]
                       if "flags" in e["spec"] and "named_scalars" in e["spec"])
    assert with_scalars >= REAL_MIN_PAIRS, \
        f"only {with_scalars}/{len(doc['materials'])} specs have real scalars"
