"""Generate the `mpl_arena_v2_a` layout -- the "helix" arrangement.

    python scripts/evr_arena_v2_layout.py --clusters <clusters.json> --out <layout.json>

THE DESIGN
----------
Stock arena is FLAT-symmetric: almost every obstacle sits in a left/right pair
at the same height, so the map reads as two mirrored side lanes plus a centre
tube, and the fast route down it is a straight line. Moving those pairs around
while keeping them level -- which is what the first pass did -- rearranges the
furniture without changing that.

This lays the field out on a **rotating ring** instead. Each obstacle is placed
at an angle `theta` in the (x, y) cross-section, and `theta` advances with `z`,
so the gaps between obstacles corkscrew down the map. The consequences that
matter in play:

* the quickest line is a slalom that changes height, not a straight side lane;
* cover appears at a different clock position every few metres, so a defender
  cannot hold one lane and see everything;
* the centre tube stays open at the kickoff and pinches twice on the way out,
  giving two natural contest points per half instead of one.

Objects are also turned to face the axis and resized within the +-20% budget,
with the biggest pieces kept nearest the walls so the middle stays passable.

FAIRNESS
--------
Every slot here describes the `z > 0` half. The other half is generated by the
arena's own symmetry, the 180-degree turn about the y axis (`x, z -> -x, -z`),
which is the symmetry the stock map already has. A rotation `R` in this half
becomes `P R P` in the other, `P = diag(-1, 1, -1)`, so the two ends are
genuinely identical and neither team gets the better side.

EXCEPTIONS
----------
* `shoulder` and `pole` keep their stock positions by request; only their size
  changes.
* `shield` takes a non-uniform scale -- wider and shorter. That is only legal
  because its instance rotation is axis-aligned; on a tilted instance a
  non-uniform world scale cannot be written back into the row's
  (quaternion, scale) pair and `evr_geo_move` refuses it rather than shearing.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

#: cross-section the ring is inscribed in. The shell is x +-16.1, y +-9.0; this
#: keeps a ~1.5 m margin so a rotated object cannot clip the wall.
RX, RY = 12.6, 6.9

#: degrees of twist per metre of z. Over the 5..33 m half that is ~150 degrees,
#: which is enough to move cover through a full clock face on the way out.
TWIST = 5.4
#: angle at z = 0.
THETA0 = 18.0


def ring(z, radius_frac, phase):
    """A point on the rotating ring: `radius_frac` of the cross-section."""
    t = math.radians(THETA0 + TWIST * z + phase)
    return [round(RX * radius_frac * math.cos(t), 2),
            round(RY * radius_frac * math.sin(t), 2),
            round(z, 2)]


#: (name, z, radius fraction, phase, scale, spin about the long axis)
#: One entry per cluster in the z > 0 half; 32 of them, matching the 64 clusters.
#: `spin` turns the object about z so it presents an edge to the lane rather
#: than a face -- the deflection that makes a slalom out of a straight run.
SLOTS = [
    # ── centre: the kickoff. On-axis pieces stay on-axis so the launch is clean.
    ("double_diamond", 8.5,  0.00,   0, 1.18, 40),
    ("devil",          6.2,  0.78,   0, 1.12, 25),
    ("station",        9.0,  0.95,  70, 1.10, 15),
    ("kernal",        11.2,  0.72, 140, 1.15, 55),
    ("popcorn",       12.4,  0.88, 215, 0.88, 30),
    ("station",       13.4,  0.95, 285, 1.10, 15),
    ("kernal",        14.6,  0.72, 320, 1.15, 55),
    ("popcorn",       15.6,  0.88,  35, 0.88, 30),
    ("angel",         10.4,  0.78, 180, 1.12, 25),
    # ── mid field: the contested band. Bigger cover, wider spread.
    ("bowtie",        19.0,  0.00,   0, 1.20, 30),
    ("crystal",       20.6,  0.86,  95, 1.14, 60),
    ("pacman",        22.4,  0.66, 165, 0.86, 45),
    ("pacman",        22.4,  0.66, 345, 0.86, 45),
    ("diamond",       24.2,  0.00,   0, 1.20,  0),
    ("nugget",        25.0,  0.90, 250, 1.18, 20),
    ("nugget",        25.0,  0.90,  70, 1.18, 20),
    # ── approach: breaks the sight line to the goal without walling it off.
    ("ghost",         27.6,  0.80,  20, 1.10, 35),
    ("ghost",         27.6,  0.80, 200, 1.10, 35),
    ("nest",          29.0,  0.00,   0, 1.15,  0),
    ("boot",          30.4,  0.74, 110, 1.12, 50),
    ("boot",          30.4,  0.74, 290, 1.12, 50),
    ("shield",        28.85, None,  0,  None,  0),
    ("shoulder",      32.4,  None,  0, 1.16,   0),
    ("shoulder",      32.4,  None,  0, 1.16,   0),
    ("pole",          31.9,  None,  0, None,   0),
    ("pole",          31.9,  None,  0, None,   0),
    # ── spawn chambers: opened out, kept clear of the tunnel mouth.
    ("spawn_tri",     67.0,  None,  0, 1.10,  20),
    ("spawn_tri",     67.0,  None,  0, 1.10,  20),
    ("spawn_b",       64.0,  None,  0, 1.15,  30),
    ("spawn_b",       64.0,  None,  0, 1.15,  30),
    ("spawn_c",       64.0,  None,  0, 1.15,  30),
    ("spawn_d",       70.0,  None,  0, 1.12,  45),
]

#: objects that keep their stock centre; only size / spin apply.
HOLD = {"shoulder", "pole", "shield"}
#: spawn-chamber pieces get a modest push away from the tunnel axis instead of
#: a ring position -- the chamber is only ~8 m across and the launch tube runs
#: straight through it.
SPAWN_PUSH = {"spawn_tri": [0.0, 3.2, 0.0], "spawn_b": [1.6, 3.6, 0.0],
              "spawn_c": [2.2, 2.6, 0.0], "spawn_d": [0.0, 4.2, 0.0]}


#: the 180-degree turn about y that maps one half of the arena onto the other.
P = np.diag([-1.0, 1.0, -1.0])
#: clearance a placed object must keep from anything already in the map.
CLEAR = 0.25
#: the search the solver walks when a nominal ring slot is blocked, in order of
#: increasing disturbance to the design: turn around the ring first, then pull
#: the radius in or out, then slide along z.
SEARCH = ([(dp, 0.0, 0.0) for dp in (0, 12, -12, 24, -24, 36, -36, 48, -48, 60, -60,
                                     75, -75, 90, -90, 110, -110, 130, -130, 150, -150, 180)]
          + [(dp, dr, 0.0) for dr in (-0.08, 0.08, -0.16, 0.16, -0.24, 0.24)
             for dp in (0, 20, -20, 45, -45, 70, -70, 100, -100, 140, -140, 180)]
          + [(dp, dr, dz) for dz in (-1.2, 1.2, -2.4, 2.4, -3.6, 3.6)
             for dr in (0.0, -0.12, 0.12, -0.24, 0.24)
             for dp in (0, 30, -30, 60, -60, 100, -100, 150, -150, 180)])


def spin_z(deg):
    t = math.radians(deg)
    c, s = math.cos(t), math.sin(t)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def placed_box(cl, target, R, S):
    lo, hi = np.array(cl["min"]), np.array(cl["max"])
    ctr = (lo + hi) / 2
    corners = np.array([[lo[0] if k & 1 else hi[0], lo[1] if k & 2 else hi[1],
                         lo[2] if k & 4 else hi[2]] for k in range(8)])
    w = ((R @ np.diag(S)) @ (corners - ctr).T).T + np.asarray(target, float)
    return w.min(0), w.max(0)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--clusters", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--dir", default=r"H:\pcvr-extracted")
    a = ap.parse_args(argv)

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import evr_geo_move as geo

    clusters = json.loads(Path(a.clusters).read_text())
    lv = geo.Level(Path(a.dir), "576ed3f8428ebc4b")
    moving = {c for v in clusters.values() for cl in v for c in cl["phys"]}
    keep, base = [], 0
    for verts, comp in zip(lv.pverts, lv.pcomp):
        for cid in np.unique(comp):
            if int(cid) + base not in moving:
                keep.append(verts[comp == cid])
        base += 100000
    STATIC = np.concatenate(keep)
    allv = np.concatenate(lv.pverts)
    LVL_LO, LVL_HI = allv.min(0), allv.max(0)

    half = {}
    for name, cls in clusters.items():
        up = [c for c in cls if (c["min"][2] + c["max"][2]) / 2 > 0]
        up.sort(key=lambda c: (c["min"][0] + c["max"][0]) / 2)
        half[name] = up

    def free(lo, hi, taken, stock_lo, stock_hi):
        """Is this box clear of everything already placed and of the level?"""
        for ax in range(3):
            new = max(LVL_LO[ax] - lo[ax], hi[ax] - LVL_HI[ax], 0.0)
            old = max(LVL_LO[ax] - stock_lo[ax], stock_hi[ax] - LVL_HI[ax], 0.0)
            if new > old + 1e-3:
                return False
        for tlo, thi in taken:
            if (lo - CLEAR <= thi).all() and (hi + CLEAR >= tlo).all():
                return False
        hit = ((STATIC >= lo - CLEAR) & (STATIC <= hi + CLEAR)).all(1).sum()
        was = ((STATIC >= stock_lo) & (STATIC <= stock_hi)).all(1).sum()
        return hit <= was

    # fixed-position objects go down first so the ring works around them
    order = sorted(range(len(SLOTS)), key=lambda i: SLOTS[i][0] not in HOLD)
    used = {k: 0 for k in half}
    taken, moves, failed = [], [], []
    for si in order:
        name, z, frac, phase, scale, spin = SLOTS[si]
        if used.get(name, 0) >= len(half.get(name, [])):
            failed.append("%s: more slots than z>0 clusters" % name)
            continue
        cl = half[name][used[name]]
        used[name] += 1
        stock_lo, stock_hi = np.array(cl["min"]), np.array(cl["max"])
        ctr = (stock_lo + stock_hi) / 2
        S = np.array([scale] * 3, float) if scale else np.ones(3)
        if name == "shield":
            S = np.array([1.20, 0.82, 1.0])
        if name == "pole":
            S = np.array([1.0, 1.18, 1.0])
        R = spin_z(spin)
        chosen = None
        if name in HOLD:
            cand = [(0.0, 0.0, 0.0)]
        elif name in SPAWN_PUSH:
            # the spawn chamber is only ~8 m across with the launch tube running
            # straight through it, so these get a search over small pushes
            # rather than a ring position.
            sx = 1.0 if ctr[0] >= 0 else -1.0
            base_push = np.array(SPAWN_PUSH[name]) * np.array([sx, 1, 1])
            cand = [(0.0, 0.0, 0.0)]
            for ddy in (0.0, -1.2, 1.2, -2.4, 2.4, -3.6, 3.6, -4.8):
                for ddx in (0.0, 0.8 * sx, -0.8 * sx, 1.6 * sx, -1.6 * sx):
                    for ddz in (0.0, -1.5, 1.5, -3.0, 3.0):
                        cand.append((ddx, ddy, ddz))
        else:
            cand = SEARCH
        for dp, dr, dz in cand:
            if name in HOLD:
                tgt = ctr.copy()
            elif name in SPAWN_PUSH:
                tgt = ctr + base_push + np.array([dp, dr, dz])
            else:
                tgt = np.array(ring(z + dz, frac + dr, phase + dp), float)
            lo, hi = placed_box(cl, tgt, R, S)
            mlo, mhi = placed_box(cl, P @ tgt, spin_z(-spin), S)
            mlo, mhi = np.minimum(mlo, mhi), np.maximum(mlo, mhi)
            if free(lo, hi, taken, stock_lo, stock_hi) and \
               free(mlo, mhi, taken, P @ stock_hi, P @ stock_lo):
                chosen = (tgt, (lo, hi), (mlo, mhi), (dp, dr, dz))
                break
        if chosen is None:
            failed.append("%s at z=%.1f: no clear position found" % (name, z))
            continue
        tgt, box, mbox, adj = chosen
        taken.append(box)
        taken.append(mbox)
        e = {"object": name, "from": [round(float(v), 2) for v in ctr],
             "to": [round(float(v), 3) for v in tgt]}
        if not np.allclose(S, 1.0):
            e["scale"] = round(float(S[0]), 3) if np.allclose(S, S[0]) else [round(float(v), 3) for v in S]
        if spin:
            e["spin_z_deg"] = spin
        if adj != (0.0, 0.0, 0.0):
            e["solver_adjust"] = {"phase_deg": adj[0], "radius_frac": round(adj[1], 3),
                                  "z": adj[2]}
        moves.append(e)
    moves.sort(key=lambda m: (abs(m["to"][2]), m["object"]))
    doc = {"format": "evr_arena_layout", "version": 2,
           "design": "helix -- the obstacle ring rotates as z increases, so the fast "
                     "line down the map is a slalom that changes height instead of a "
                     "straight side lane",
           "symmetry": "the z>0 half is authored; the other half is the 180 degree turn "
                       "about y (x,z -> -x,-z), the stock map's own symmetry",
           "scale_budget": "0.80 - 1.20",
           "ring": {"rx": RX, "ry": RY, "twist_deg_per_m": TWIST, "theta0_deg": THETA0},
           "clearance_m": CLEAR,
           "moves": moves}
    Path(a.out).write_text(json.dumps(doc, indent=1))
    print("%-16s %-26s %-26s %-16s %-6s %s" % ("object", "from", "to", "scale", "spin", "solver"))
    for m in moves:
        print("%-16s %-26s %-26s %-16s %-6s %s"
              % (m["object"], m["from"], m["to"], m.get("scale", "-"),
                 m.get("spin_z_deg", "-"),
                 m.get("solver_adjust", "") and
                 "phase%+.0f r%+.2f z%+.1f" % (m["solver_adjust"]["phase_deg"],
                                               m["solver_adjust"]["radius_frac"],
                                               m["solver_adjust"]["z"])))
    print("\nplaced %d of %d slots, clearance %.2f m" % (len(moves), len(SLOTS), CLEAR))
    if failed:
        print("UNPLACED:")
        for f in failed:
            print("   " + f)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
